#
#
#

DOC_ROOT = ..
include ../Makefile.inc

srcs	= AccessType.md \
	AlertType.md4 \
	Alignment.md4 \
	AnimationState.md4 \
	Authorize.md4 \
	Axis.md4 \
	ButtonState.md4 \
	ComparisonResult.md4 \
	Device.md4 \
	Distribution.md4 \
	ExitCode.md4 \
	FileType.md4 \
	FontSize.md4 \
	Language.md4 \
	LogLevel.md4 \
	SortOrder.md4 \
	SymbolSize.md4 \
	Symbols.md4 \
	TokenType.md4

dsts	= $(srcs:.md4=.md)

all: $(dsts)

clean:
	rm -f $(dsts)

