#
#
#

DOC_ROOT = ..
include	../Makefile.inc

srcs	= Char.md4 \
	  Oval.md4 \
	  Point.md4 \
	  Range.md4 \
	  Rect.md4 \
	  Result.md4 \
	  Size.md4 \
	  Vector.md4
dsts	= $(srcs:.md4=.md)

all: $(dsts)

clean:
	rm -f $(dsts)

