#
#
#

DOC_ROOT = ..
include ../Makefile.inc

srcs	= Char.md4 \
	  Color.md4 \
	  Colors.md4 \
	  Console.md4 \
	  Curses.md4 \
	  Date.md4 \
	  Environment.md4 \
	  EscapeCode.md4 \
	  EscapeSequence.md4 \
	  EscapeSequences.md4 \
	  File.md4 \
	  FileManager.md4 \
	  GraphicsContext.md4 \
	  Graphics.md4 \
	  Image.md4 \
	  JSON.md4 \
	  Math.md4 \
	  Pipe.md4 \
	  Preference.md4 \
	  Process.md4 \
	  Record.md4 \
	  Semaphore.md4 \
	  SpriteScene.md4 \
	  SpriteNode.md4 \
	  SFSymbol.md4 \
	  StringStream.md4 \
	  Table.md4 \
	  Thread.md4 \
	  URL.md4

dsts	= $(srcs:.md4=.md)

all: $(dsts)

clean:
	rm -f $(dsts)

