#
#
#

DOC_ROOT = ..
include ../Makefile.inc

srcs	= DataTypeFormat.md4 \
	  eJSON.md4 \
	  eJSTN.md4 \
	  Properties.md4 \
	  Table.md4 \
	  ValueTypeCode.md4
dsts	= $(srcs:.md4=.md)

all: $(dsts)

clean:
	rm -f $(dsts)

